[package]
name = "idem-handler"
version = "0.1.0"
edition = "2024"

[dependencies]
idem-config = {path = "../idem-config"}
idem-macro = {path = "../idem-macro"}

[dev-dependencies]
tokio = { version = "1.44.1" , features = ["macros", "rt"]}
