[package]
name = "idem-encoder"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
fnv = "1.0.7"

[dev-dependencies]
criterion = "0.5.1"
env_logger = "0.11.7"

[[bench]]
name = "encode_benchmarks"
harness = false
