[package]
name = "idem-openapi"
version = "0.1.0"
edition = "2024"

[dependencies]
idem-config = {path = "../idem-config"}

oas3 = "0.16.1"
jsonschema = "0.30.0"
serde_json = "1.0.140"
once_cell = "1.21.3"
dashmap = "7.0.0-rc2"
serde = { version = "1.0.219", features = ["derive"] }


